# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer # files end with exactly one newline
  - repo: local
    hooks:
      - id: prettier
        name: prettier (settings in .prettierrc.json)
        entry: bunx prettier --write
        language: system
        types_or: [ts, tsx]
      - id: typecheck
        name: typecheck (tsc --noEmit)
        entry: bun run typecheck
        language: system
        pass_filenames: false
